services:
  flask: # flask周りの設定
    build: 
      context: ./flask
      dockerfile: Dockerfile
    command: uwsgi --socket :8001 --module app.wsgi --py-autoreload 1 --logto /tmp/mylog.log
    volumes: # longのvolumesは自動でフォルダが作られることによるエラーの対策
      - type: bind # volumesはbind mount 指定したフォルダとコンテナ内のフォルダが共有される
        source: "./flask" # "共有元"
        target: "/code" # "共有先"
      - socket:/tmp
    tty: true
    hostname: flask

  nginx:
    image: nginx:latest
    ports:
      - "8081:8081"
    volumes:
      - type: bind
        source: "./nginx/nginx.conf"
        target: /etc/nginx/conf.d/default.conf
      - socket:tmp

  volumes:
    socket: